### ISSUE TITLE
Aquarius is not indexing Moonbase Alpha

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/aquarius#543]
Aquarius is currently not indexing the moonbase alpha network. This means that the market is not working on Moonbase Alpha. 

The chain IDs that Aquarius is indexing are shown here: https://aquarius.oceanprotocol.com/api/v1/aquarius/chains/list 

The market is getting a 500 error returned from aquarius: 
![500 error - 2021-08-03_13-58](https://user-images.githubusercontent.com/20739535/128012490-124c74ec-7e91-4a8a-82f6-32bdd1760536.png)

**Comment by md00ux** [comment]
@jamiehewitt15 , could you check now ?

**Comment by jamiehewitt15** [comment]
Still getting the same 500 error when loading the market on Moonbase Alpha. It only seems to give the error if Moonbase Alpha is the only network that you are on

**Comment by md00ux** [comment]
these are the related errors in Aquarius:

![image](https://user-images.githubusercontent.com/54084524/128085172-05d19533-e503-417b-b944-e77d92202731.png)


![image](https://user-images.githubusercontent.com/54084524/128085373-e91ebcc0-9140-4a53-ad0d-083b1fb31da5.png)

**Comment by mihaisc** [comment]
This is still an issue. And this also happens on polygon mumbai.

**Comment by calina-c** [comment]
With Aquarius 3.0.2 running on a remote machine, the indexing works and I can query the new ES endpoint.

@jamiehewitt15 I assume this is the old Aquarius. Can you confirm? Can you also send me a full response? 500 doesn't automatically mean the assets are not indexed, it could be something else.

@mihaisc @md00ux what is the status of the v3.0.2 deployment? Maybe this is a wild goose chase and we are trying to fix something that is already fixed. Worst case scenario, if v3.0.2 is not ready for deployment, maybe we can make a test with aquarius2.oceanprotocol.com on Moonbeam and Mumbai?

**Comment by md00ux** [comment]
Aquarius deployed on Moonbeam and Mumbai and should be accessible through aquarius2.oceanprotocol.com endpoint (v3.0.2).

**Comment by mihaisc** [comment]
You can easily test this [here](https://market-13bh6vl0j-oceanprotocol.vercel.app/search?sort=created&sortOrder=desc) and select the desired networks. Moonbeam seems to be working in 3.0.2 but mumbai is still not indexing anything

**Comment by calina-c** [comment]
I selected Mumbai, there is no 500 error. There are simply no results returned. When I try indexing Mumbai, I get no metadata created events. Can someone publish an asset on Mumbai, to make sure we have results?

**Comment by calina-c** [comment]
@mihaisc any updates on this?

**Comment by mihaisc** [comment]
No, please try and publish an asset using the api to test this.

**Comment by calina-c** [comment]
Marian published an asset today during a call with me https://market-13bh6vl0j-oceanprotocol.vercel.app/asset/did:op:f23E410e48621839Ba374f81a2882801D0334B74. it seems to be correctly indexed and shown on the marketplace.

The issues we had were with our broken Mumbai faucet and the broken ETH faucet in Mumbai itself. It was a rough ride but it seems we're in the clear now.
